env:
  global:
  - CC_TEST_REPORTER_ID=705ff985a4346f862fc8e1bf06de67f4e7f54ffa0676b794819cbc97a8926db9
language: ruby
rvm:
- 2.6.3
services:
- postgresql
before_install:
- gem update --system
- gem install bundler
install: gem install rails
notifications:
- false
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
- cp config/database.yml.travis config/database.yml
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
  > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- "./cc-test-reporter before-build"
script:
- bundle install
- rails db:migrate
- rails test
after_script:
- "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"
deploy:
  provider: heroku
  api_key:
    secure: dd27Ebbpi1m+5WiQ4zZ+VLE0R/XXUrLxZ2Q8AWLujRv36XH4jj7MNGZQtzHX71wQ32nO3eav4F2vrGwsPx22tKdbWvzekGUMe498HKvvkV3EBI0veFUk1cm3EK/YHrQYfMRzn3C4LoVtX7400+tFmI4cNa+NHjQeBgeAKzM+5P1Jpkzidzk6/nkDcwsXiWf/fdskQL4Q9/JCzEI3a/agYt960K0vDGtRfc/NETGrFigEcnxHbhPnwhDfYPVnMznIfR9dZoH/S1l6g3+L/DHNpD0zocFftHGO4aGP8zqb8OyvYW043W7iRjSj4EdlDGBUWpa61Nc8aVAtKfTlXdaMSCAcCSIVS1bSJ0RXU2dViZw8bj0OatzAd/gX5+emkJVsQcTkB3vS/XzcU0lOPiKA3jZpqouNF5SU3S2HnGLfV3ejD9VzexBhZM6YfqiLeI5lxo5OoCoDXDuz7n+09WaU1OPXROtpu9p5sHOyRTJaUzBrGxa4C3I2t/6lsF3VscHzsBzGJfZu18WkJ5/2mtr7racddxdJXtbkyIAbaNuKZXOLz4vUNfKXXr2XWb9/IgufEEB2Z06eNQS9n0O50r8IiXdvKowv/AilZzo73LnU3115eAmXVo52kg57tlVm74O+H9dFAxiv8xcNGLWtL1iKsQnR8A/Qvnf7/roTAKszMTU=
  strategy: git
  app:
    master: bolah-sample-app
    staging: bolah-sample-app-staging
  run:
  - sleep 10
  - rails db:migrate
  - rails db:seed
